# Generated by Django 4.1.1 on 2022-09-25 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Тип')),
                ('color', models.CharField(db_index=True, max_length=20, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы новостей',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('summary', models.TextField(verbose_name='Краткое описание')),
                ('text', models.TextField(verbose_name='Полное описание')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_news.type', verbose_name='Тип новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-id'],
            },
        ),
    ]
